### ISSUE TITLE
performance  problem

### ISSUE THREAD

**Issue by yale8848** [florent37/Android-NoSql#2]
i see use SharedPreferences still，i think performance is big problem

**Comment by florent37** [comment]
You can try another implementation of Data storage, maybe using ''paper'' instead of sharedprefs as storage of this lib will have better performance

**Comment by yale8848** [comment]
ok thanks

**Comment by florent37** [comment]
I published a class using Paper if you want to try

https://github.com/florent37/Android-NoSql/blob/master/android-nosql-paper/src/main/java/florent37/github/com/androidnosql/paper/PaperDataSaver.java

**Comment by yale8848** [comment]
yeah, i see ,very thank you :)
